import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum AppLanguage { french, english }

class LanguageService extends ChangeNotifier {
  static final LanguageService _instance = LanguageService._internal();
  factory LanguageService() => _instance;
  LanguageService._internal();

  AppLanguage _currentLanguage = AppLanguage.french;
  AppLanguage get currentLanguage => _currentLanguage;

  static final Map<String, String> _frenchTranslations = {
    'app_name': 'Nora',
    'home': 'Accueil',
    'search': 'Rechercher',
    'cart': 'Panier',
    'profile': 'Profil',
    'settings': 'Paramètres',
    'orders': 'Commandes',
    'shops': 'Boutiques',
    'products': 'Produits',
    'videos': 'Vidéos',
    'notifications': 'Notifications',
    'language': 'Langue',
    'theme': 'Thème',
    'dark_mode': 'Mode sombre',
    'light_mode': 'Mode clair',
    'logout': 'Déconnexion',
    'login': 'Connexion',
    'register': 'Inscription',
    'email': 'Email',
    'password': 'Mot de passe',
    'confirm_password': 'Confirmer le mot de passe',
    'name': 'Nom',
    'phone': 'Téléphone',
    'address': 'Adresse',
    'shop': 'Boutique',
    'my_shop': 'Ma boutique',
    'create_shop': 'Créer ma boutique',
    'edit_shop': 'Modifier ma boutique',
    'add_product': 'Ajouter un produit',
    'edit_product': 'Modifier le produit',
    'delete_product': 'Supprimer le produit',
    'share': 'Partager',
    'share_shop': 'Partager la boutique',
    'follow': 'Suivre',
    'unfollow': 'Ne plus suivre',
    'like': 'J\'aime',
    'unlike': 'Je n\'aime plus',
    'add_to_cart': 'Ajouter au panier',
    'buy_now': 'Acheter maintenant',
    'checkout': 'Commander',
    'order_history': 'Historique des commandes',
    'order_details': 'Détails de la commande',
    'order_status': 'Statut de la commande',
    'pending': 'En attente',
    'confirmed': 'Confirmée',
    'preparing': 'En préparation',
    'ready': 'Prête',
    'in_delivery': 'En livraison',
    'delivered': 'Livrée',
    'cancelled': 'Annulée',
    'delivery': 'Livraison',
    'tracking': 'Suivi',
    'delivery_address': 'Adresse de livraison',
    'payment_method': 'Mode de paiement',
    'total': 'Total',
    'subtotal': 'Sous-total',
    'shipping': 'Livraison',
    'discount': 'Remise',
    'promo_code': 'Code promo',
    'apply': 'Appliquer',
    'remove': 'Supprimer',
    'quantity': 'Quantité',
    'price': 'Prix',
    'description': 'Description',
    'category': 'Catégorie',
    'categories': 'Catégories',
    'all_products': 'Tous les produits',
    'all_shops': 'Toutes les boutiques',
    'all_videos': 'Toutes les vidéos',
    'trending': 'Tendances',
    'recommended': 'Recommandé',
    'new': 'Nouveau',
    'sale': 'Promotion',
    'rating': 'Note',
    'reviews': 'Avis',
    'no_reviews': 'Aucun avis',
    'write_review': 'Écrire un avis',
    'submit': 'Envoyer',
    'cancel': 'Annuler',
    'save': 'Enregistrer',
    'delete': 'Supprimer',
    'edit': 'Modifier',
    'close': 'Fermer',
    'open': 'Ouvrir',
    'loading': 'Chargement...',
    'error': 'Erreur',
    'success': 'Succès',
    'warning': 'Attention',
    'info': 'Information',
    'yes': 'Oui',
    'no': 'Non',
    'ok': 'OK',
    'search_placeholder': 'Que cherchez-vous?',
    'no_results': 'Aucun résultat',
    'try_again': 'Réessayer',
    'wishlist': 'Favoris',
    'add_to_wishlist': 'Ajouter aux favoris',
    'remove_from_wishlist': 'Retirer des favoris',
    'empty_wishlist': 'Votre liste de favoris est vide',
    'mb_coins': 'MB Coins',
    'balance': 'Solde',
    'earn': 'Gagner',
    'spend': 'Dépenser',
    'rewards': 'Récompenses',
    'transactions': 'Transactions',
    'withdraw': 'Retirer',
    'mb_shop': 'Boutique MB',
    'purchases': 'Achats',
    'admin': 'Administrateur',
    'merchant': 'Commerçant',
    'client': 'Client',
    'driver': 'Livreur',
    'chat': 'Chat',
    'message': 'Message',
    'send': 'Envoyer',
    'type_message': 'Tapez votre message...',
    'online': 'En ligne',
    'offline': 'Hors ligne',
    'last_seen': 'Vu il y a',
    // Paramètres
    'appearance': 'Apparence',
    'dark_mode_title': 'Mode sombre',
    'dark_mode_subtitle': 'Activer le thème sombre',
    'language_section': 'Langue',
    'language_french': 'Français',
    'language_french_subtitle': 'Langue par défaut',
    'language_english': 'English',
    'language_english_subtitle': 'Langue par défaut',
    'notifications_section': 'Notifications',
    'notifications_title': 'Notifications',
    'notifications_subtitle': 'Activer toutes les notifications',
    'security_section': 'Sécurité',
    'biometric_login': 'Authentification biométrique',
    'biometric_login_subtitle': 'Utiliser votre empreinte digitale',
    'about_section': 'À propos',
    'version_title': 'Version',
    'terms_title': 'Conditions d\'utilisation',
    'terms_dialog_title': 'Conditions d\'utilisation',
    'terms_dialog_content': 'Conditions d\'utilisation de NORA Marketplace...\n\n1. Acceptation des conditions\nEn utilisant notre application, vous acceptez ces conditions.\n\n2. Compte utilisateur\nVous êtes responsable de la confidentialité de votre compte.\n\n3. Achats et paiements\nLes transactions sont sécurisées via notre plateforme.\n\n4. Livraison\nLes délais de livraison sont indicatifs.\n\n5. Retours et remboursements\nConformément à la loi en vigueur.\n\n6. Modification des conditions\nNous pouvons modifier ces conditions à tout moment.',
    'close': 'Fermer',
    'exit_app_title': 'Quitter l\'application',
    'exit_app_content': 'Voulez-vous vraiment quitter NORA Marketplace ?',
    'exit_app_confirm': 'Quitter',
    'exit_app_cancel': 'Annuler',
    // Authentification
    'sign_in': 'Connexion',
    'sign_up': 'Inscription',
    'forgot_password': 'Mot de passe oublié?',
    'username': 'Nom d\'utilisateur',
    'role': 'Rôle',
    'role_client': 'Client',
    'role_merchant': 'Commerçant',
    'role_driver': 'Livreur',
    'verify_email': 'Vérifiez votre email',
    'verify_email_description': 'Nous avons envoyé un code de validation à',
    'enter_code': 'Entrez le code à 6 chiffres',
    'validate': 'Valider',
    'resend_code': 'Renvoyer le code',
    'resend_in': 'Renvoyer dans',
    'seconds': 's',
    'code_sent': 'Code de validation envoyé à votre email',
    'code_expired': 'Code expiré ou invalide',
    'code_incorrect': 'Code incorrect',
    'email_already_used': 'Cet email est déjà utilisé',
    'new_code_sent': 'Nouveau code envoyé',
    'dont_have_account': 'Vous n\'avez pas de compte?',
    'already_have_account': 'Vous avez déjà un compte?',
    'please_enter_email': 'Veuillez entrer votre adresse email pour recevoir un code de confirmation.',
    'email_required': 'Email requis',
    'email_invalid': 'Email invalide',
    'password_required': 'Mot de passe requis',
    'password_min_length': '6 caractères minimum',
    'confirm_password_required': 'Confirmation requise',
    'passwords_not_match': 'Les mots de passe ne correspondent pas',
    'phone_required': 'Numéro de téléphone requis',
    'username_required': 'Nom d\'utilisateur requis',
    'email_or_password_incorrect': 'Email ou mot de passe incorrect',
    'registration_error': 'Erreur lors de l\'inscription',
    'login_error': 'Erreur de connexion',
    'server_error': 'Erreur de connexion au serveur',
    'city': 'Ville',
    'country': 'Pays',
    // Profil
    'edit_profile': 'Modifier le profil',
    'my_profile': 'Mon profil',
    'full_name': 'Nom complet',
    'your_name': 'Votre nom',
    'name_required': 'Nom requis',
    'phone_number': 'Numéro de téléphone',
    'phone_hint': '+237 6XX XXX XXX',
    'address_hint': 'Rue, quartier, résidence...',
    'city_hint': 'Douala, Yaoundé...',
    'save': 'Enregistrer',
    'profile_updated': 'Profil mis à jour avec succès',
    'profile_update_error': 'Erreur lors de la mise à jour du profil',
    'photo_not_saved': 'Photo non sauvegardée',
    'please_reconnect': 'Veuillez vous reconnecter',
    'retry': 'Réessayer',
    'impossible_to_load_profile': 'Impossible de charger le profil',
    'loading_error': 'Erreur de chargement',
    'member_since': 'Membre depuis',
    'edit_my_profile': 'Modifier mon profil',
    'orders': 'Commandes',
    'spending': 'Dépenses',
    'my_mb_purchases': 'Mes achats MB',
    'my_rewards': 'Mes récompenses',
    'about': 'À propos',
    'faq': 'FAQ',
    'connect_to_see_profile': 'Connectez-vous pour voir votre profil',
    'login': 'Se connecter',
    'nora_marketplace': 'NORA Marketplace',
    'version': 'Version',
    'buy_and_sell_easily': 'Achetez et vendez en toute simplicité',
    'all_rights_reserved': 'Tous droits réservés',
    // Produits admin
    'confirm_delete': 'Confirmer la suppression',
    'product_deleted': 'Produit supprimé',
    'no_products': 'Aucun produit',
    'add_first_product': 'Ajouter votre premier produit',
    'price_required': 'Prix requis',
    'category_required': 'Catégorie requise',
    'compare_price': 'Prix de comparaison',
    'stock': 'Stock',
    'variants': 'Variantes',
    'add_variant': 'Ajouter une variante',
    'active': 'Actif',
    'visible_in_app': 'Visible dans l\'application',
    'update': 'Mettre à jour',
    'create': 'Créer',
    'add_images': 'Ajouter des images',
    'subcategory': 'Sous-catégorie',
    'subcategory_required': 'Veuillez sélectionner une sous-catégorie',
    // Boutiques
    'shop_name': 'Nom de la boutique',
    'shop_description': 'Description de la boutique',
    'shop_address': 'Adresse de la boutique',
    'shop_phone': 'Téléphone de la boutique',
    'shop_email': 'Email de la boutique',
    'shop_logo': 'Logo de la boutique',
    'shop_banner': 'Bannière de la boutique',
    'shop_status': 'Statut de la boutique',
    'shop_status_pending': 'En attente',
    'shop_status_active': 'Active',
    'shop_status_rejected': 'Refusée',
    'shop_certified': 'Certifiée',
    'shop_not_certified': 'Non certifiée',
    'shop_certified_at': 'Certifiée le',
    'request_certification': 'Demander la certification',
    'certification_request_sent': 'Demande de certification envoyée',
    'certification_benefits': 'Avantages de la certification',
    'certification_badge': 'Badge de certification',
    'certification_visibility': 'Meilleure visibilité',
    'certification_trust': 'Confiance accrue',
    'certification_sales': 'Augmentation des ventes',
    'delivery_cities': 'Villes de livraison',
    'delivery_price': 'Prix de livraison',
    'free_delivery_min_amount': 'Livraison gratuite à partir de',
    'delivery_type': 'Type de livraison',
    'delivery_type_standard': 'Standard',
    'delivery_type_express': 'Express',
    'delivery_type_both': 'Les deux',
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'opening_hours': 'Horaires d\'ouverture',
    'monday': 'Lundi',
    'tuesday': 'Mardi',
    'wednesday': 'Mercredi',
    'thursday': 'Jeudi',
    'friday': 'Vendredi',
    'saturday': 'Samedi',
    'sunday': 'Dimanche',
    'closed': 'Fermé',
    'open': 'Ouverture',
    'close': 'Fermeture',
    'facebook_url': 'Facebook',
    'instagram_url': 'Instagram',
    'whatsapp_number': 'WhatsApp',
    'social_media': 'Réseaux sociaux',
    'shop_validation': 'Validation des boutiques',
    'approve_shop': 'Approuver',
    'reject_shop': 'Rejeter',
    'shop_approved': 'Boutique approuvée',
    'shop_rejected': 'Boutique refusée',
    'no_shops_pending': 'Aucune boutique en attente',
    'shop_created_success': 'Boutique créée avec succès',
    'shop_updated_success': 'Boutique mise à jour avec succès',
    'shop_deleted_success': 'Boutique supprimée avec succès',
    'shop_validation_required': 'Votre boutique doit être validée par l\'administrateur avant d\'ajouter des produits',
    'my_shops': 'Mes boutiques',
    'no_shops_yet': 'Vous n\'avez pas encore de boutique',
    'create_first_shop': 'Créez votre première boutique',
    'certify_your_shop': 'Certifiez votre boutique',
    'certify_shop_description': 'Obtenez le badge de certification et gagnez la confiance de vos clients',
    'request_later': 'Plus tard',
  };

  static final Map<String, String> _englishTranslations = {
    'app_name': 'Nora',
    'home': 'Home',
    'search': 'Search',
    'cart': 'Cart',
    'profile': 'Profile',
    'settings': 'Settings',
    'orders': 'Orders',
    'shops': 'Shops',
    'products': 'Products',
    'videos': 'Videos',
    'notifications': 'Notifications',
    'language': 'Language',
    'theme': 'Theme',
    'dark_mode': 'Dark Mode',
    'light_mode': 'Light Mode',
    'logout': 'Logout',
    'login': 'Login',
    'register': 'Register',
    'email': 'Email',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'name': 'Name',
    'phone': 'Phone',
    'address': 'Address',
    'shop': 'Shop',
    'my_shop': 'My Shop',
    'create_shop': 'Create My Shop',
    'edit_shop': 'Edit My Shop',
    'add_product': 'Add Product',
    'edit_product': 'Edit Product',
    'delete_product': 'Delete Product',
    'share': 'Share',
    'share_shop': 'Share Shop',
    'follow': 'Follow',
    'unfollow': 'Unfollow',
    'like': 'Like',
    'unlike': 'Unlike',
    'add_to_cart': 'Add to Cart',
    'buy_now': 'Buy Now',
    'checkout': 'Checkout',
    'order_history': 'Order History',
    'order_details': 'Order Details',
    'order_status': 'Order Status',
    'pending': 'Pending',
    'confirmed': 'Confirmed',
    'preparing': 'Preparing',
    'ready': 'Ready',
    'in_delivery': 'In Delivery',
    'delivered': 'Delivered',
    'cancelled': 'Cancelled',
    'delivery': 'Delivery',
    'tracking': 'Tracking',
    'delivery_address': 'Delivery Address',
    'payment_method': 'Payment Method',
    'total': 'Total',
    'subtotal': 'Subtotal',
    'shipping': 'Shipping',
    'discount': 'Discount',
    'promo_code': 'Promo Code',
    'apply': 'Apply',
    'remove': 'Remove',
    'quantity': 'Quantity',
    'price': 'Price',
    'description': 'Description',
    'category': 'Category',
    'categories': 'Categories',
    'all_products': 'All Products',
    'all_shops': 'All Shops',
    'all_videos': 'All Videos',
    'trending': 'Trending',
    'recommended': 'Recommended',
    'new': 'New',
    'sale': 'Sale',
    'rating': 'Rating',
    'reviews': 'Reviews',
    'no_reviews': 'No Reviews',
    'write_review': 'Write a Review',
    'submit': 'Submit',
    'cancel': 'Cancel',
    'save': 'Save',
    'delete': 'Delete',
    'edit': 'Edit',
    'close': 'Close',
    'open': 'Open',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Info',
    'yes': 'Yes',
    'no': 'No',
    'ok': 'OK',
    'search_placeholder': 'What are you looking for?',
    'no_results': 'No Results',
    'try_again': 'Try Again',
    'wishlist': 'Wishlist',
    'add_to_wishlist': 'Add to Wishlist',
    'remove_from_wishlist': 'Remove from Wishlist',
    'empty_wishlist': 'Your wishlist is empty',
    'mb_coins': 'MB Coins',
    'balance': 'Balance',
    'earn': 'Earn',
    'spend': 'Spend',
    'rewards': 'Rewards',
    'transactions': 'Transactions',
    'withdraw': 'Withdraw',
    'mb_shop': 'MB Shop',
    'purchases': 'Purchases',
    'admin': 'Admin',
    'merchant': 'Merchant',
    'client': 'Client',
    'driver': 'Driver',
    'chat': 'Chat',
    'message': 'Message',
    'send': 'Send',
    'type_message': 'Type your message...',
    'online': 'Online',
    'offline': 'Offline',
    'last_seen': 'Last seen',
    // Settings
    'appearance': 'Appearance',
    'dark_mode_title': 'Dark Mode',
    'dark_mode_subtitle': 'Enable dark theme',
    'language_section': 'Language',
    'language_french': 'Français',
    'language_french_subtitle': 'Default language',
    'language_english': 'English',
    'language_english_subtitle': 'Default language',
    'notifications_section': 'Notifications',
    'notifications_title': 'Notifications',
    'notifications_subtitle': 'Enable all notifications',
    'security_section': 'Security',
    'biometric_login': 'Biometric authentication',
    'biometric_login_subtitle': 'Use your fingerprint',
    'about_section': 'About',
    'version_title': 'Version',
    'terms_title': 'Terms of Service',
    'terms_dialog_title': 'Terms of Service',
    'terms_dialog_content': 'NORA Marketplace Terms of Service...\n\n1. Acceptance of Terms\nBy using our application, you agree to these terms.\n\n2. User Account\nYou are responsible for the confidentiality of your account.\n\n3. Purchases and Payments\nTransactions are secured through our platform.\n\n4. Delivery\nDelivery times are indicative.\n\n5. Returns and Refunds\nIn accordance with applicable law.\n\n6. Modification of Terms\nWe can modify these terms at any time.',
    'close': 'Close',
    'exit_app_title': 'Exit Application',
    'exit_app_content': 'Do you really want to exit NORA Marketplace?',
    'exit_app_confirm': 'Exit',
    'exit_app_cancel': 'Cancel',
    // Authentication
    'sign_in': 'Sign In',
    'sign_up': 'Sign Up',
    'forgot_password': 'Forgot Password?',
    'username': 'Username',
    'role': 'Role',
    'role_client': 'Client',
    'role_merchant': 'Merchant',
    'role_driver': 'Driver',
    'verify_email': 'Verify your email',
    'verify_email_description': 'We have sent a verification code to',
    'enter_code': 'Enter the 6-digit code',
    'validate': 'Validate',
    'resend_code': 'Resend code',
    'resend_in': 'Resend in',
    'seconds': 's',
    'code_sent': 'Verification code sent to your email',
    'code_expired': 'Code expired or invalid',
    'code_incorrect': 'Incorrect code',
    'email_already_used': 'This email is already used',
    'new_code_sent': 'New code sent',
    'dont_have_account': 'Don\'t have an account?',
    'already_have_account': 'Already have an account?',
    'please_enter_email': 'Please enter your email address to receive a confirmation code.',
    'email_required': 'Email required',
    'email_invalid': 'Invalid email',
    'password_required': 'Password required',
    'password_min_length': 'Minimum 6 characters',
    'confirm_password_required': 'Confirmation required',
    'passwords_not_match': 'Passwords do not match',
    'phone_required': 'Phone number required',
    'username_required': 'Username required',
    'email_or_password_incorrect': 'Email or password incorrect',
    'registration_error': 'Registration error',
    'login_error': 'Login error',
    'server_error': 'Server connection error',
    'city': 'City',
    'country': 'Country',
    // Profile
    'edit_profile': 'Edit Profile',
    'my_profile': 'My Profile',
    'full_name': 'Full Name',
    'your_name': 'Your name',
    'name_required': 'Name required',
    'phone_number': 'Phone Number',
    'phone_hint': '+237 6XX XXX XXX',
    'address_hint': 'Street, neighborhood, residence...',
    'city_hint': 'Douala, Yaoundé...',
    'save': 'Save',
    'profile_updated': 'Profile updated successfully',
    'profile_update_error': 'Error updating profile',
    'photo_not_saved': 'Photo not saved',
    'please_reconnect': 'Please reconnect',
    'retry': 'Retry',
    'impossible_to_load_profile': 'Unable to load profile',
    'loading_error': 'Loading error',
    'member_since': 'Member since',
    'edit_my_profile': 'Edit my profile',
    'orders': 'Orders',
    'spending': 'Spending',
    'my_mb_purchases': 'My MB Purchases',
    'my_rewards': 'My Rewards',
    'about': 'About',
    'faq': 'FAQ',
    'connect_to_see_profile': 'Log in to see your profile',
    'login': 'Log in',
    'nora_marketplace': 'NORA Marketplace',
    'version': 'Version',
    'buy_and_sell_easily': 'Buy and sell easily',
    'all_rights_reserved': 'All rights reserved',
    // Products admin
    'confirm_delete': 'Confirm deletion',
    'product_deleted': 'Product deleted',
    'no_products': 'No products',
    'add_first_product': 'Add your first product',
    'price_required': 'Price required',
    'category_required': 'Category required',
    'compare_price': 'Compare price',
    'stock': 'Stock',
    'variants': 'Variants',
    'add_variant': 'Add variant',
    'active': 'Active',
    'visible_in_app': 'Visible in app',
    'update': 'Update',
    'create': 'Create',
    'add_images': 'Add images',
    'subcategory': 'Subcategory',
    'subcategory_required': 'Please select a subcategory',
    // Shops
    'shop_name': 'Shop Name',
    'shop_description': 'Shop Description',
    'shop_address': 'Shop Address',
    'shop_phone': 'Shop Phone',
    'shop_email': 'Shop Email',
    'shop_logo': 'Shop Logo',
    'shop_banner': 'Shop Banner',
    'shop_status': 'Shop Status',
    'shop_status_pending': 'Pending',
    'shop_status_active': 'Active',
    'shop_status_rejected': 'Rejected',
    'shop_certified': 'Certified',
    'shop_not_certified': 'Not Certified',
    'shop_certified_at': 'Certified on',
    'request_certification': 'Request Certification',
    'certification_request_sent': 'Certification request sent',
    'certification_benefits': 'Certification Benefits',
    'certification_badge': 'Certification Badge',
    'certification_visibility': 'Better Visibility',
    'certification_trust': 'Increased Trust',
    'certification_sales': 'Increased Sales',
    'delivery_cities': 'Delivery Cities',
    'delivery_price': 'Delivery Price',
    'free_delivery_min_amount': 'Free Delivery From',
    'delivery_type': 'Delivery Type',
    'delivery_type_standard': 'Standard',
    'delivery_type_express': 'Express',
    'delivery_type_both': 'Both',
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'opening_hours': 'Opening Hours',
    'monday': 'Monday',
    'tuesday': 'Tuesday',
    'wednesday': 'Wednesday',
    'thursday': 'Thursday',
    'friday': 'Friday',
    'saturday': 'Saturday',
    'sunday': 'Sunday',
    'closed': 'Closed',
    'open': 'Opening',
    'close': 'Closing',
    'facebook_url': 'Facebook',
    'instagram_url': 'Instagram',
    'whatsapp_number': 'WhatsApp',
    'social_media': 'Social Media',
    'shop_validation': 'Shop Validation',
    'approve_shop': 'Approve',
    'reject_shop': 'Reject',
    'shop_approved': 'Shop Approved',
    'shop_rejected': 'Shop Rejected',
    'no_shops_pending': 'No pending shops',
    'shop_created_success': 'Shop created successfully',
    'shop_updated_success': 'Shop updated successfully',
    'shop_deleted_success': 'Shop deleted successfully',
    'shop_validation_required': 'Your shop must be validated by the administrator before adding products',
    'my_shops': 'My Shops',
    'no_shops_yet': 'You don\'t have any shops yet',
    'create_first_shop': 'Create your first shop',
    'certify_your_shop': 'Certify Your Shop',
    'certify_shop_description': 'Get the certification badge and gain customer trust',
    'request_later': 'Later',
  };

  Future<void> initialize() async {
    final prefs = await SharedPreferences.getInstance();
    final languageCode = prefs.getString('language') ?? 'fr';
    _currentLanguage = languageCode == 'en' ? AppLanguage.english : AppLanguage.french;
    notifyListeners();
  }

  Future<void> setLanguage(AppLanguage language) async {
    _currentLanguage = language;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language', language == AppLanguage.english ? 'en' : 'fr');
    notifyListeners();
  }

  String translate(String key) {
    final translations = _currentLanguage == AppLanguage.english 
        ? _englishTranslations 
        : _frenchTranslations;
    return translations[key] ?? key;
  }

  String get currentLanguageCode => _currentLanguage == AppLanguage.english ? 'en' : 'fr';
}
