name: nora
description: "Nora Marketplace - Application de e-commerce"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # ✅ Localisations (indispensable pour MaterialLocalizations)
  flutter_localizations:
    sdk: flutter
  
  # Navigation
  go_router: ^13.0.0
  
  # Réseau
  http: ^1.2.0
  dio: ^5.4.0
  web_socket_channel: ^2.4.0
  http_parser: ^4.0.2 
  # Stockage local
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  flutter_cache_manager: ^3.3.1
  
  # Vidéo
  video_player: ^2.8.3
  chewie: ^1.7.4
  video_compress: ^3.1.2
  video_thumbnail: ^0.5.3
  
  # Images
  cached_network_image: ^3.3.0
  image_picker: ^1.0.7
  
  # Maps & Géolocalisation
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  
  # QR Code & Scanner
  mobile_scanner: ^4.0.1
  qr_flutter: ^4.1.0
  
  # UI & Animations
  flutter_staggered_animations: ^1.1.0
  animate_do: ^4.0.0
  
  # Utilitaires
  intl: ^0.20.2
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  
  # Notifications
  flutter_local_notifications: ^20.1.0
  
  # Permissions & Device Info
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.0
  connectivity_plus: ^5.0.0
  
  # Style
  cupertino_icons: ^1.0.8
  firebase_core: ^4.10.0
  firebase_messaging: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png